version: "3"

services:

  webapp:         
    image: alessandrolanni/php7.4-apache-custom
    volumes:
      - ./src:/var/www
    ports:
      - "8000:80"
    networks:
      - backend

networks:
  backend:
